import type { QRType, QRTypeDefinition } from "@/types/qr";
import {
  urlQrSchema,
  textQrSchema,
  emailQrSchema,
  phoneQrSchema,
  smsQrSchema,
  whatsappQrSchema,
  wifiQrSchema,
  vcardQrSchema,
  eventQrSchema,
  pdfQrSchema,
  imagesQrSchema,
  audioQrSchema,
  videoQrSchema,
  notYetImplementedQrSchema,
} from "@/lib/validation/qr";
import {
  buildUrlPayload,
  buildTextPayload,
  buildEmailPayload,
  buildPhonePayload,
  buildSmsPayload,
  buildWhatsAppPayload,
  buildWifiPayload,
  buildVCardPayload,
  buildEventPayload,
  buildPdfPayload,
  buildImagesPayload,
  buildAudioPayload,
  buildVideoPayload,
} from "@/lib/qr/payload-builders";

/**
 * Type-erases a strongly-typed payload builder for storage in the
 * heterogeneous registry below. Call sites that know the concrete QR type
 * should import the builder directly from `payload-builders` instead.
 */
function toGenericBuilder<T>(
  builder: (input: T) => string,
): (input: Record<string, unknown>) => string {
  return (input) => builder(input as T);
}

export const qrTypeRegistry: Record<QRType, QRTypeDefinition> = {
  url: {
    key: "url",
    label: "URL / Link",
    icon: "link",
    staticSupport: true,
    dynamicSupport: true,
    fields: urlQrSchema,
    payloadBuilder: toGenericBuilder(buildUrlPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: true,
    previewUpdateStrategy: "immediate",
  },
  text: {
    key: "text",
    label: "Text",
    icon: "type",
    staticSupport: true,
    dynamicSupport: false,
    fields: textQrSchema,
    payloadBuilder: toGenericBuilder(buildTextPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  email: {
    key: "email",
    label: "Email",
    icon: "mail",
    staticSupport: true,
    dynamicSupport: false,
    fields: emailQrSchema,
    payloadBuilder: toGenericBuilder(buildEmailPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  phone: {
    key: "phone",
    label: "Phone Call",
    icon: "phone",
    staticSupport: true,
    dynamicSupport: false,
    fields: phoneQrSchema,
    payloadBuilder: toGenericBuilder(buildPhonePayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  sms: {
    key: "sms",
    label: "SMS",
    icon: "message-square",
    staticSupport: true,
    dynamicSupport: false,
    fields: smsQrSchema,
    payloadBuilder: toGenericBuilder(buildSmsPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  vcard: {
    key: "vcard",
    label: "vCard / Contact",
    icon: "contact",
    staticSupport: true,
    dynamicSupport: false,
    fields: vcardQrSchema,
    payloadBuilder: toGenericBuilder(buildVCardPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  whatsapp: {
    key: "whatsapp",
    label: "WhatsApp",
    icon: "message-circle",
    staticSupport: true,
    dynamicSupport: true,
    fields: whatsappQrSchema,
    payloadBuilder: toGenericBuilder(buildWhatsAppPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: true,
    previewUpdateStrategy: "immediate",
  },
  wifi: {
    key: "wifi",
    label: "Wi-Fi",
    icon: "wifi",
    staticSupport: true,
    dynamicSupport: false,
    fields: wifiQrSchema,
    payloadBuilder: toGenericBuilder(buildWifiPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  pdf: {
    key: "pdf",
    label: "PDF",
    icon: "file-text",
    staticSupport: false,
    dynamicSupport: true,
    fields: pdfQrSchema,
    payloadBuilder: toGenericBuilder(buildPdfPayload),
    needsStorage: true,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  app: {
    key: "app",
    label: "App Store / Play Store",
    icon: "smartphone",
    staticSupport: true,
    dynamicSupport: true,
    fields: notYetImplementedQrSchema,
    needsStorage: false,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  images: {
    key: "images",
    label: "Images / Gallery",
    icon: "images",
    staticSupport: false,
    dynamicSupport: true,
    fields: imagesQrSchema,
    payloadBuilder: toGenericBuilder(buildImagesPayload),
    needsStorage: true,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  video: {
    key: "video",
    label: "Video",
    icon: "video",
    staticSupport: true,
    dynamicSupport: true,
    fields: videoQrSchema,
    payloadBuilder: toGenericBuilder(buildVideoPayload),
    needsStorage: false,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  social: {
    key: "social",
    label: "Social Media",
    icon: "share-2",
    staticSupport: false,
    dynamicSupport: true,
    fields: notYetImplementedQrSchema,
    needsStorage: false,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  event: {
    key: "event",
    label: "Event",
    icon: "calendar",
    staticSupport: true,
    dynamicSupport: false,
    fields: eventQrSchema,
    payloadBuilder: toGenericBuilder(buildEventPayload),
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  barcode_2d: {
    key: "barcode_2d",
    label: "2D Barcode",
    icon: "scan-line",
    staticSupport: true,
    dynamicSupport: false,
    fields: notYetImplementedQrSchema,
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: false,
    previewUpdateStrategy: "immediate",
  },
  multi_link: {
    key: "multi_link",
    label: "Multiple Links / Link-in-bio",
    icon: "layers",
    staticSupport: false,
    dynamicSupport: true,
    fields: notYetImplementedQrSchema,
    needsStorage: false,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  menu: {
    key: "menu",
    label: "Menu",
    icon: "utensils",
    staticSupport: false,
    dynamicSupport: true,
    fields: notYetImplementedQrSchema,
    needsStorage: true,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  feedback: {
    key: "feedback",
    label: "Feedback",
    icon: "star",
    staticSupport: false,
    dynamicSupport: true,
    fields: notYetImplementedQrSchema,
    needsStorage: false,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  audio: {
    key: "audio",
    label: "MP3 / Audio",
    icon: "music",
    staticSupport: false,
    dynamicSupport: true,
    fields: audioQrSchema,
    payloadBuilder: toGenericBuilder(buildAudioPayload),
    needsStorage: true,
    needsLandingPage: true,
    supportsAnalytics: true,
    previewUpdateStrategy: "debounced",
  },
  location: {
    key: "location",
    label: "Location",
    icon: "map-pin",
    staticSupport: true,
    dynamicSupport: true,
    fields: notYetImplementedQrSchema,
    needsStorage: false,
    needsLandingPage: false,
    supportsAnalytics: true,
    previewUpdateStrategy: "immediate",
  },
};

export function getQrTypeDefinition(type: QRType): QRTypeDefinition {
  return qrTypeRegistry[type];
}

export function listQrTypeDefinitions(): QRTypeDefinition[] {
  return Object.values(qrTypeRegistry);
}
